import React, { useMemo, useState } from "react";
import "./styles.css";

const screens = ["welcome", "profile", "home", "ready", "round", "hole", "review", "plan", "prompt", "practice", "progress"];
const labels = { welcome: "Welcome", profile: "Profile", home: "Home", ready: "Ready to Play", round: "Round", hole: "Hole input", review: "Round review", plan: "Next Round Plan", prompt: "Smart prompt", practice: "Practice", progress: "Progress" };
const pars = [4,5,3,4,4,3,4,5,4,4,3,5,4,4,3,4,5,4];

function initialRound(){
  return Array.from({length:18},(_,i)=>({
    hole:i+1, par:pars[i], score:pars[i]+1, saved:i<4,
    tee:i===1?["Miss right"]:i===3?["Fairway hit"]:[],
    approach:i===1||i===2?["Miss short"]:i===3?["Green hit"]:[],
    green:i===2?["Poor chip"]:[], putting:i===0?["2-putt"]:i===1?["3-putt"]:[]
  }));
}

function analyse(round){
  const saved=round.filter(h=>h.saved); const sample=saved.length?saved:round.slice(0,4);
  const count=(fn)=>sample.filter(fn).length;
  const short=count(h=>h.approach.includes("Miss short"));
  const right=count(h=>h.tee.includes("Miss right"));
  const penalty=count(h=>h.tee.includes("Penalty")||h.green.includes("Bunker miss"));
  const putts=count(h=>h.putting.includes("3-putt"));
  const chips=count(h=>h.green.includes("Poor chip"));
  const early=count(h=>h.hole<=3&&h.score>h.par+1);
  const front=count(h=>h.hole<=9);
  const items=[];
  if(short>=2) items.push({title:"Approach pattern", detail:"Most missed greens came from approaches finishing short.", source:`Based on ${sample.length} logged holes`, action:"Club up and aim for the middle of the green.", confidence:"Strong pattern"});
  if(right>=1||penalty>=1) items.push({title:"Tee-shot risk", detail:"Right-side misses are creating recovery shots and bringing doubles into play.", source:"Seen across your saved holes", action:"Use a safer club when trouble sits right.", confidence:"Worth watching"});
  if(putts>=1) items.push({title:"Putting distance control", detail:"The biggest putting risk is leaving yourself too much work from the first putt.", source:"Observed from post-hole putting tags", action:"Lag first putts into a 3ft circle.", confidence:"Early signal"});
  if(chips>=1) items.push({title:"Around the green", detail:"Short-game mistakes are turning missed greens into dropped shots.", source:"Based on your around-green tags", action:"Get the first chip on the green before chasing the flag.", confidence:"Early signal"});
  if(early>=1||front>=3) items.push({title:"Opening holes", detail:"Your early holes need a steadier start and fewer aggressive choices.", source:"Based on your first few logged holes", action:"Play the first three holes with the safest target in mind.", confidence:"Recurring phase to track"});
  if(!items.length) items.push({title:"Course management", detail:"No major leak stands out yet. Keep logging to build a clearer pattern.", source:"Based on the holes saved so far", action:"Choose the shot that removes the worst miss.", confidence:"Needs more rounds"});
  return items.slice(0,3);
}

function Phone({children}){return <main className="page"><section className="phone"><div className="notch"/><div className="screen">{children}</div></section></main>}
function Header({title,sub,back,hideBack}){return <div className="header">{!hideBack&&<button className="back" onClick={back}>‹</button>}<div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div></div>}
function Card({children,dark=false,soft=false}){return <div className={`card ${dark?"dark":""} ${soft?"soft":""}`}>{children}</div>}
function Btn({children,onClick,secondary=false}){return <button onClick={onClick} className={`btn ${secondary?"secondary":""}`}>{children}</button>}
function Pill({children,on,click}){return <button onClick={click} className={`pill ${on?"on":""}`}>{children}</button>}
function Nav({go}){return <div className="nav">{[["home","⛳","Home"],["ready","◌","Ready"],["round","＋","Round"],["plan","◎","Plan"],["practice","◉","Practice"]].map(([s,i,t])=><button key={s} onClick={()=>go(s)}><span>{i}</span>{t}</button>)}</div>}

function Welcome({go}){return <Phone><div className="stack fill"><div><div className="logo">⛳</div><h1>SugarCaddy</h1><p className="lead">An easier way to track your round, spot patterns and play your next round with a clearer plan.</p></div><Card><ul><li>Simple post-hole tracking</li><li>Clear insight from your playing patterns</li><li>Practice that transfers to the course</li></ul></Card><Btn onClick={()=>go("profile")}>Get started</Btn></div></Phone>}
function Profile({go,back}){const[h,setH]=useState(14),[goal,setGoal]=useState("Break 80");return <Phone><Header title="Your golfer profile" sub="A quick setup so advice feels relevant." back={back}/><div className="stack"><Card><p className="eyebrow">Current handicap</p><div className="counter"><button onClick={()=>setH(Math.max(1,h-1))}>−</button><strong>{h}</strong><button onClick={()=>setH(h+1)}>+</button></div></Card><div><p className="eyebrow">Main goal</p><div className="pills">{["Break 90","Break 85","Break 80","Single figures"].map(x=><Pill key={x} on={goal===x} click={()=>setGoal(x)}>{x}</Pill>)}</div></div><Btn onClick={()=>go("home")}>Continue</Btn></div></Phone>}
function Home({go,back}){return <Phone><Header title="Today" sub="Get ready, play, then review what mattered." hideBack/><div className="stack"><Card dark><p className="eyebrow light">Before you tee off</p><h2>Ready to Play</h2><p>A short warm-up to loosen up, find rhythm and settle your first tee focus.</p><button className="white" onClick={()=>go("ready")}>Start prep</button></Card><Card><h3>How better rounds are built</h3><p className="muted">A simple rhythm that helps you learn from each round and carry improvements into the next one.</p><div className="journey">{["Play","Review","Practise","Improve"].map((x,i)=><React.Fragment key={x}><div><b>{i+1}</b><span>{x}</span></div>{i<3&&<em/>}</React.Fragment>)}</div></Card><Btn onClick={()=>go("round")}>Start round capture</Btn></div><Nav go={go}/></Phone>}
function Ready({go,back}){const moves=["Shoulder turns","Hip openers","Hamstring sweep","Wrist circles","Three easy swings"];return <Phone><Header title="Ready to Play" sub="Four minutes. Calm body, clear first tee." back={back}/><div className="stack bottomGap"><Card dark><p className="eyebrow light">First tee reset</p><h2>Loosen up and find rhythm</h2><p>Simple movements you can do by the car park or practice green.</p><p className="note">Better starts usually lead to steadier opening holes.</p></Card>{moves.map((m,i)=><Card key={m}><div className="row"><b className="num">{i+1}</b><div><h3>{m}</h3><p className="muted">30–45 seconds. Smooth and easy.</p></div></div></Card>)}<Card><p className="eyebrow">First tee focus</p><h3>Pick a safe target. Commit to one smooth swing.</h3></Card><Btn onClick={()=>go("round")}>Start round</Btn></div><Nav go={go}/></Phone>}
function HoleGrid({round,select}){return <div className="holes">{round.map((h,i)=><button key={h.hole} onClick={()=>select(i)} className={`${h.saved?"saved":""}`}><b>{h.hole}</b><span>{h.saved?"Saved":""}</span></button>)}</div>}
function Round({go,back,round,setHole,lastSaved}){const done=round.filter(h=>h.saved).length;const current=round.find(h=>!h.saved)||round[17];return <Phone><Header title="Round capture" sub="Simple post-hole tracking" back={back}/><div className="stack bottomGap">{lastSaved&&<div className="savedMsg">Hole {lastSaved} saved. Ready for the next one.</div>}<Card><div className="between"><div><p className="eyebrow">Current hole</p><h2>Hole {current.hole}</h2></div><span className="badge">Par {current.par}</span></div><div className="bar"><i style={{width:`${done/18*100}%`}}/></div><p className="muted">{done} of 18 holes saved</p></Card><HoleGrid round={round} select={(i)=>{setHole(i);go("hole")}}/><Card soft>Most golfers log each hole walking to the next tee.</Card><Btn onClick={()=>go("review")}>Finish and review</Btn></div><Nav go={go}/></Phone>}
function TagSection({title,hint,options,selected,toggle}){return <Card><h3>{title}</h3><p className="muted">{hint}</p><div className="pills">{options.map(o=><Pill key={o} on={selected.includes(o)} click={()=>toggle(o)}>{o}</Pill>)}</div></Card>}
function Hole({go,back,round,setRound,hole,setHole,setLastSaved}){const h=round[hole];const update=p=>setRound(prev=>prev.map((x,i)=>i===hole?{...x,...p}:x));const toggle=(sec,tag)=>update({[sec]:h[sec].includes(tag)?h[sec].filter(x=>x!==tag):[...h[sec],tag]});const save=()=>{update({saved:true});setLastSaved(h.hole);setHole(Math.min(hole+1,17));go("round")};return <Phone><Header title={`Hole ${h.hole}`} sub={`Par ${h.par} · Quick round capture`} back={back}/><div className="stack scroll"><Card><p className="eyebrow">Score</p><div className="counter"><button onClick={()=>update({score:Math.max(1,h.score-1)})}>−</button><strong>{h.score}</strong><button onClick={()=>update({score:h.score+1})}>+</button></div></Card><TagSection title="Tee shot" hint="Only the first shot on par 4s and par 5s." options={["Fairway hit","Miss left","Miss right","Penalty","Recovery shot"]} selected={h.tee} toggle={t=>toggle("tee",t)}/><TagSection title="Approach" hint="The shot into the green." options={["Green hit","Miss short","Miss left","Miss right","Miss long"]} selected={h.approach} toggle={t=>toggle("approach",t)}/><TagSection title="Around green" hint="Only if you missed the green." options={["Up and down","Poor chip","Bunker miss","Good recovery"]} selected={h.green} toggle={t=>toggle("green",t)}/><TagSection title="Putting" hint="What happened once you reached the green." options={["1-putt","2-putt","3-putt"]} selected={h.putting} toggle={t=>toggle("putting",t)}/><Btn onClick={save}>Save hole and continue</Btn></div></Phone>}
function Review({go,back,round}){const insights=analyse(round);return <Phone><Header title="Round review" sub="Clear patterns from your saved holes." back={back}/><div className="stack bottomGap"><Card dark><p className="eyebrow light">Round reflection</p><h2>You were closer than the score suggests</h2><p>Most dropped shots came from one recurring pattern rather than your whole game breaking down.</p><p className="note">{insights[0].source}</p></Card><Card><div className="between"><h3>What stayed solid</h3><span className="good">Positive trend</span></div><p>Your putting stayed steady and avoided extra damage once you reached the green.</p><p className="muted">Based on your saved holes</p></Card>{insights.map(x=><Card key={x.title}><div className="between"><h3>{x.title}</h3><span className="badge">{x.confidence}</span></div><p>{x.detail}</p><p className="muted">{x.source}</p></Card>)}<Card><p className="eyebrow">Credibility note</p><p>Your plan is based on repeated behaviours you logged during the round, not generic tips. More rounds will make the pattern clearer.</p></Card><div className="two"><Btn onClick={()=>go("plan")}>Next Round Plan</Btn><Btn secondary onClick={()=>go("practice")}>Practice ideas</Btn></div></div><Nav go={go}/></Phone>}
function PlanCard({n,title,body,evidence}){return <Card><div className="row"><b className="num">{n}</b><div><h3>{title}</h3><p>{body}</p><p className="muted">{evidence}</p></div></div></Card>}
function Plan({go,back,round}){const main=analyse(round)[0];return <Phone><Header title="Next Round Plan" sub="Three simple rules to take to the course." back={back}/><div className="stack bottomGap"><PlanCard n="1" title={main.action} body="Use this as your main playing rule next round. Keep it simple and repeat it before each relevant shot." evidence={main.source}/><PlanCard n="2" title="Play the first three holes safely" body="Start steady. Pick targets that remove the worst miss and avoid chasing early birdies." evidence="Your opening holes are now being tracked as a round phase."/><PlanCard n="3" title="Protect against doubles" body="A bogey after a poor shot is fine. The scorecard damage comes from forcing the next one." evidence="This is the fastest improvement route for most mid-handicap golfers."/><div className="two"><Btn onClick={()=>go("prompt")}>Start round</Btn><Btn secondary onClick={()=>go("practice")}>Practise</Btn></div></div><Nav go={go}/></Phone>}
function Prompt({go,back,round}){const insight=analyse(round)[0];return <Phone><Header title="Hole 4" sub="Smart prompt · based on your plan" back={back}/><div className="stack bottomGap"><Card dark><p className="eyebrow light">Before you hit</p><h2>{insight.action}</h2><p>{insight.detail}</p></Card><Card><p className="eyebrow">Why this prompt appears</p><p>{insight.source}. This prompt only appears when it connects to your current plan.</p></Card><Btn onClick={()=>go("round")}>Log this hole</Btn></div><Nav go={go}/></Phone>}
function Drill({title,body}){return <Card><div className="row"><b className="tick">✓</b><div><h3>{title}</h3><p>{body}</p></div></div></Card>}
function Practice({go,back,round}){const insight=analyse(round)[0];return <Phone><Header title="Practice plan" sub="Short, practical and built for your next round." back={back}/><div className="stack bottomGap"><Card dark><p className="eyebrow light">Primary focus</p><h2>{insight.title}</h2><p>{insight.action}</p></Card><Drill title="Start Here · 10 mins" body="Hit 15 balls from 100–150 yards using one extra club. Focus only on solid contact and finishing pin-high, not attacking flags."/><Drill title="Pressure Practice · 15 mins" body="Create a fairway-width target on the range. Hit 10 drives or hybrids and score one point every time the ball finishes inside your target zone."/><Drill title="Take It To The Course · 10 mins" body="Finish with 9 random golf shots. Change club and target every ball. Step back each time and rehearse your full on-course routine before swinging."/><Btn onClick={()=>go("progress")}>Mark practice complete</Btn></div><Nav go={go}/></Phone>}
function Progress({go,back}){return <Phone><Header title="Progress" sub="Simple trends. No stats overload." back={back}/><div className="stack bottomGap"><Card dark><p className="eyebrow light">Current pattern</p><h2>Approach misses are reducing</h2><p>Your short/right approach pattern has softened over the last three logged rounds.</p></Card><Card><h3>Trend confidence</h3>{[["Round 1","Short/right misses","High"],["Round 2","Fewer short misses","Improving"],["Round 3","More greens hit","Stronger"]].map(([r,l,s])=><div className="trend" key={r}><div><b>{r}</b><p>{l}</p></div><span>{s}</span></div>)}</Card><Btn onClick={()=>go("plan")}>View updated plan</Btn></div><Nav go={go}/></Phone>}

export default function App(){
  const[screen,setScreen]=useState("welcome"),[history,setHistory]=useState([]),[round,setRound]=useState(initialRound),[hole,setHole]=useState(4),[lastSaved,setLastSaved]=useState(null);
  const go=s=>{if(!screens.includes(s))return;setHistory(h=>[...h,screen]);setScreen(s)};
  const back=()=>setHistory(h=>{if(!h.length)return h;setScreen(h[h.length-1]);return h.slice(0,-1)});
  const props={go,back,round,setRound,hole,setHole,lastSaved,setLastSaved};
  return <div>{screen==="welcome"&&<Welcome {...props}/>} {screen==="profile"&&<Profile {...props}/>} {screen==="home"&&<Home {...props}/>} {screen==="ready"&&<Ready {...props}/>} {screen==="round"&&<Round {...props}/>} {screen==="hole"&&<Hole {...props}/>} {screen==="review"&&<Review {...props}/>} {screen==="plan"&&<Plan {...props}/>} {screen==="prompt"&&<Prompt {...props}/>} {screen==="practice"&&<Practice {...props}/>} {screen==="progress"&&<Progress {...props}/>}<div className="side">{screens.map(s=><button key={s} onClick={()=>setScreen(s)} className={screen===s?"active":""}>{labels[s]}</button>)}</div></div>
}
