import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const TAGS = ['Fairway hit', 'GIR', 'Penalty', 'Missed short', 'Missed right', '3-putt', 'Recovery shot'];
const holes = Array.from({ length: 18 }, (_, i) => ({
  hole: i + 1,
  par: [4, 5, 3, 4, 4, 3, 5, 4, 4, 4, 3, 5, 4, 4, 3, 5, 4, 4][i],
  yards: [392, 515, 168, 371, 426, 154, 538, 401, 389, 412, 176, 529, 365, 448, 149, 550, 405, 430][i],
  score: [5, 6, 4, 5, 5, 3, 6, 5, 4, 5, 4, 6, 4, 6, 3, 6, 5, 5][i],
  tags: i === 6 ? ['Penalty', 'Recovery shot'] : i === 13 ? ['Missed right', 'Penalty'] : i % 4 === 0 ? ['Missed short', 'Missed right'] : i % 5 === 0 ? ['3-putt'] : []
}));

function diagnose(round) {
  const totals = { approach: 0, tee: 0, putting: 0, gir: 0 };
  round.forEach(h => {
    if (h.tags.includes('Missed short')) totals.approach += 1;
    if (h.tags.includes('Missed right')) totals.approach += 1;
    if (h.tags.includes('Penalty')) totals.tee += 2;
    if (h.tags.includes('Recovery shot')) totals.tee += 1;
    if (h.tags.includes('3-putt')) totals.putting += 1;
    if (!h.tags.includes('GIR') && h.par > 3) totals.gir += 0.4;
  });
  const leaks = [
    { key: 'Approach', title: '100–150 yard approaches', detail: 'Short/right misses are costing you shots.', value: totals.approach, rule: 'Take one more club', body: 'From 100–150 yards, club up and aim centre-left of the green.' },
    { key: 'Tee shots', title: 'Tee shots on tight holes', detail: 'Penalties and recovery shots are creating doubles.', value: totals.tee, rule: 'Hybrid on tight holes', body: 'When there is trouble right or the fairway feels narrow, keep driver in the bag.' },
    { key: 'Putting', title: 'Putting distance control', detail: 'Three-putts are adding avoidable shots.', value: totals.putting, rule: 'Lag to a 3ft zone', body: 'Focus on speed control. The first putt is about leaving a simple second putt.' },
    { key: 'GIR', title: 'Greens in regulation', detail: 'Missing greens is putting pressure on short game.', value: totals.gir, rule: 'Aim centre of green', body: 'Avoid sucker pins. Give yourself a putt and remove the short-sided miss.' }
  ].sort((a,b) => b.value - a.value);
  return leaks.filter(l => l.value > 0).slice(0,3);
}

function Button({ children, onClick, secondary=false }) {
  return <button type="button" onClick={onClick} className={secondary ? 'btn secondary' : 'btn'}>{children}</button>;
}
function Card({ children, dark=false }) { return <div className={dark ? 'card dark' : 'card'}>{children}</div>; }
function Pill({ active, children, onClick }) { return <button type="button" className={active ? 'pill active' : 'pill'} onClick={onClick}>{children}</button>; }
function Shell({ children }) { return <main className="page"><section className="phone"><div className="notch"/><div className="screen">{children}</div></section></main>; }
function Header({ title, sub, back }) { return <div className="header">{back && <button className="back" onClick={back}>‹</button>}<div><h2>{title}</h2>{sub && <p>{sub}</p>}</div></div>; }
function Nav({ go }) { return <div className="nav"><button onClick={()=>go('home')}>⛳<span>Home</span></button><button onClick={()=>go('round')}>＋<span>Round</span></button><button onClick={()=>go('plan')}>◎<span>Plan</span></button><button onClick={()=>go('progress')}>▦<span>Progress</span></button></div>; }

function Welcome({ go }) { return <Shell><div className="hero"><div className="icon">⛳</div><h1>Smart Caddie Loop</h1><p className="lead">A simple plan for your next round, based on what actually cost you shots last time.</p><Card><p>✓ Play with fewer bad decisions</p><p>✓ Find your biggest scoring leaks</p><p>✓ Practise what transfers to the course</p></Card><Button onClick={()=>go('profile')}>Get started</Button></div></Shell>; }
function Profile({ go, back }) { const [hcp,setHcp]=useState(14); const [miss,setMiss]=useState('Short right'); return <Shell><Header title="Your golfer profile" sub="Keep this quick. We learn from rounds." back={back}/><div className="stack"><Card><p className="label">Current handicap</p><div className="counter"><button onClick={()=>setHcp(Math.max(1,hcp-1))}>−</button><strong>{hcp}</strong><button onClick={()=>setHcp(hcp+1)}>+</button></div></Card><div><p className="label">Typical miss</p><div className="tags">{['Short right','Short left','Long','Right','Left','Thin','Heavy'].map(x=><Pill key={x} active={miss===x} onClick={()=>setMiss(x)}>{x}</Pill>)}</div></div><Button onClick={()=>go('baseline')}>Continue</Button></div></Shell>; }
function Baseline({ go, back }) { return <Shell><Header title="Build your baseline" sub="Your first plan comes after one round." back={back}/><div className="stack"><Card><h3>What we’ll capture</h3><p>○ Score per hole</p><p>○ Fairway, green and penalties</p><p>○ Simple miss tags</p></Card><Card dark><p className="label light">MVP principle</p><h3>No shot-by-shot admin during your round.</h3></Card><Button onClick={()=>go('home')}>Set up app</Button></div></Shell>; }
function Home({ go }) { return <Shell><Header title="Today" sub="Track one round to unlock your plan."/><div className="stack padbottom"><Card dark><p className="label light">Next step</p><h1>Track your first round</h1><p>We’ll turn it into your first Next Round Plan.</p><button className="whitebtn" onClick={()=>go('round')}>Start round</button></Card><Card><h3>How the loop works</h3><div className="grid"><span>Play</span><span>Diagnose</span><span>Practise</span><span>Improve</span></div></Card></div><Nav go={go}/></Shell>; }
function Round({ go, back, round, setCurrentHole }) { return <Shell><Header title="Round capture" sub="Post-hole input. Fast taps only." back={back}/><div className="roundlist padbottom"><Card><p className="label">Course</p><strong>Local test round</strong></Card><div className="holes">{round.map(h=><button key={h.hole} onClick={()=>{setCurrentHole(h.hole-1); go('hole');}}><span>Hole</span><strong>{h.hole}</strong><small>{h.score} shots</small></button>)}</div><Button onClick={()=>go('summary')}>Finish round</Button></div><Nav go={go}/></Shell>; }
function Hole({ go, back, round, setRound, currentHole }) { const h=round[currentHole]; function toggle(tag){setRound(prev=>prev.map((x,i)=> i!==currentHole ? x : {...x,tags:x.tags.includes(tag)?x.tags.filter(t=>t!==tag):[...x.tags,tag]}));} function score(delta){setRound(prev=>prev.map((x,i)=> i!==currentHole ? x : {...x,score:Math.max(1,x.score+delta)}));} return <Shell><Header title={`Hole ${h.hole}`} sub={`Par ${h.par} · ${h.yards} yards`} back={back}/><div className="stack"><Card><p className="label">Score</p><div className="counter"><button onClick={()=>score(-1)}>−</button><strong>{h.score}</strong><button onClick={()=>score(1)}>+</button></div></Card><div><p className="label">What happened?</p><div className="tags">{TAGS.map(t=><Pill key={t} active={h.tags.includes(t)} onClick={()=>toggle(t)}>{t}</Pill>)}</div></div><Button onClick={()=>go('round')}>Save hole</Button></div></Shell>; }
function Summary({ go, back, leaks, round }) { const total=round.reduce((a,h)=>a+h.score,0); return <Shell><Header title="Round summary" sub={`You shot ${total}. Here’s what cost you shots.`} back={back}/><div className="stack padbottom"><Card dark><p className="label light">Biggest leak</p><h1>{leaks[0]?.title || 'Course management'}</h1><p>{leaks[0]?.detail || 'No major leak detected.'}</p></Card>{leaks.map(l=><Card key={l.key}><div className="leak"><div><strong>{l.key}</strong><p>{l.detail}</p></div><b>+{l.value.toFixed(1)}</b></div></Card>)}<Button onClick={()=>go('plan')}>Create Next Round Plan</Button></div><Nav go={go}/></Shell>; }
function Plan({ go, back, leaks }) { const top = leaks.length ? leaks : [{rule:'Play simple',body:'Choose the shot that removes the biggest miss.'}]; return <Shell><Header title="Next Round Plan" sub="Three rules. No clutter." back={back}/><div className="stack padbottom">{top.map((l,i)=><Card key={i}><div className="plancard"><b>{i+1}</b><div><h3>{l.rule}</h3><p>{l.body}</p></div></div></Card>)}<Card><div className="plancard"><b>{top.length+1}</b><div><h3>Protect against doubles</h3><p>Your score improves fastest by removing blow-up holes, not chasing birdies.</p></div></div></Card><div className="twocol"><Button onClick={()=>go('prompt')}>Start round</Button><Button secondary onClick={()=>go('practice')}>Practise</Button></div></div><Nav go={go}/></Shell>; }
function Prompt({ go, back, leaks }) { const l=leaks[0] || {rule:'Play simple',body:'Choose the shot that removes the biggest miss.'}; return <Shell><Header title="Hole 4" sub="Par 4 · 371 yards" back={back}/><div className="stack padbottom"><Card dark><p className="label light">Smart prompt</p><h1>{l.rule}</h1><p>{l.body}</p></Card><Card><p className="label">Your rule</p><h3>Commit to the plan. Remove double.</h3></Card><Button onClick={()=>go('round')}>Log this hole</Button></div><Nav go={go}/></Shell>; }
function Practice({ go, back, leaks }) { const l=leaks[0] || {title:'Course management'}; return <Shell><Header title="Practice plan" sub="30 minutes before your next round." back={back}/><div className="stack padbottom"><Card dark><p className="label light">Primary focus</p><h1>{l.title}</h1><p>Build trust before taking the plan back to the course.</p></Card><Card><h3>Block 1</h3><p>12 balls from your problem range. Four balls at three targets.</p></Card><Card><h3>Block 2</h3><p>Target: 6 of 12 inside your scoring zone.</p></Card><Card><h3>Block 3</h3><p>Finish with 6 random shots. Full commitment only.</p></Card><Button onClick={()=>go('progress')}>Mark practice complete</Button></div><Nav go={go}/></Shell>; }
function Progress({ go, back }) { return <Shell><Header title="Progress" sub="Your scoring leaks over time." back={back}/><div className="stack padbottom"><Card dark><p className="label light">Estimated gain</p><h1>2.5 shots</h1><p>From better approach choices and fewer tee-shot penalties.</p></Card><Card><h3>Approach leak trend</h3>{[['Round 1','+3.0',80],['Round 2','+2.1',58],['Round 3','+1.2',22]].map(r=><div className="barrow" key={r[0]}><div><span>{r[0]}</span><span>{r[1]}</span></div><em><i style={{width:r[2]+'%'}} /></em></div>)}</Card><Button onClick={()=>go('plan')}>View updated plan</Button></div><Nav go={go}/></Shell>; }

function App(){ const [screen,setScreen]=useState('welcome'); const [history,setHistory]=useState([]); const [round,setRound]=useState(holes); const [currentHole,setCurrentHole]=useState(0); const leaks=useMemo(()=>diagnose(round),[round]); function go(s){ setHistory(h=>[...h,screen]); setScreen(s);} function back(){ setHistory(h=>{ if(!h.length) return h; setScreen(h[h.length-1]); return h.slice(0,-1);}); } const props={go,back,round,setRound,currentHole,setCurrentHole,leaks}; if(screen==='welcome')return <Welcome go={go}/>; if(screen==='profile')return <Profile {...props}/>; if(screen==='baseline')return <Baseline {...props}/>; if(screen==='home')return <Home {...props}/>; if(screen==='round')return <Round {...props}/>; if(screen==='hole')return <Hole {...props}/>; if(screen==='summary')return <Summary {...props}/>; if(screen==='plan')return <Plan {...props}/>; if(screen==='prompt')return <Prompt {...props}/>; if(screen==='practice')return <Practice {...props}/>; if(screen==='progress')return <Progress {...props}/>; return <Welcome go={go}/>; }

createRoot(document.getElementById('root')).render(<App/>);
